baseURL: "https://TheMSKHub.github.io/"
title: "The MSK Hub"
theme: PaperMod

menu:
  main:
    - name: Blog
      url: /blogs/
      weight: 10
    - name: Contact Me
      url: /contact/Contact
      weight: 30
    - name: About
      url: /about/About
      weight: 40
     
markup:
 goldmark:
   renderer:
     unsafe: true

  
params:
  homeTitle: "Welcome! I’m Mohammed Swalah, a passionate individual who work for community growth and equity."
  homeSubtitle: "Lets Make this world a better place together"
 
